// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RailwayTicketReservation.Models.Data;

#nullable disable

namespace RailwayTicketReservation.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    [Migration("20231220105640_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RailwayTicketReservation.Models.Data.Login", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.ToTable("SignIn");
                });

            modelBuilder.Entity("RailwayTicketReservation.Models.Data.Passenger", b =>
                {
                    b.Property<int>("Passenger_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Passenger_Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Booking_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Passenger_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seat_No")
                        .HasColumnType("integer");

                    b.HasKey("Passenger_Id");

                    b.ToTable("passengers");
                });

            modelBuilder.Entity("RailwayTicketReservation.Models.Data.RegisterUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MobileNo")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.ToTable("UserRegistration");
                });

            modelBuilder.Entity("RailwayTicketReservation.Models.Data.ReserveTicket", b =>
                {
                    b.Property<int>("Ticket_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Ticket_Id"));

                    b.Property<string>("Age_Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Departure_Time")
                        .HasColumnType("date");

                    b.Property<string>("From_Station")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Payment")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Return")
                        .HasColumnType("date");

                    b.Property<int>("Seat_Availability")
                        .HasColumnType("integer");

                    b.Property<int>("Seat_No")
                        .HasColumnType("integer");

                    b.Property<string>("To_Station")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ticket_Id");

                    b.ToTable("ReserveTickets");
                });

            modelBuilder.Entity("RailwayTicketReservation.Models.Data.Schedule", b =>
                {
                    b.Property<int>("Train_No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Train_No"));

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Train_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Train_No");

                    b.ToTable("trains");
                });
#pragma warning restore 612, 618
        }
    }
}
